### ISSUE TITLE
TabsRouting2 sample not working

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular-samples#668]
### Description  
TabsRouting2 not working when selecting a tab

### Steps to reproduce  

1. [Open samples](https://stackblitz.com/github/IgniteUI/igniteui-angular-samples/)
2. Go to Tabs => TabsRouting1
3. Click on View2 tab.

### Result  
The content of the tabs remains empty.

### Expected result  
The content of the tab changes.

### Attachments  
Error in console:
`preview-294996d1d7b15f951a67a.js:1 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'view2'
Error: Cannot match any routes. URL Segment: 'view2'
    at ApplyRedirects.noMatchError (apply_redirects.ts:110)
    at CatchSubscriber.eval [as selector] (apply_redirects.ts:87)
    at CatchSubscriber.error (catchError.ts:119)
    at MapSubscriber.Subscriber._error (Subscriber.ts:145)
    at MapSubscriber.Subscriber.error (Subscriber.ts:115)
    at MapSubscriber.Subscriber._error (Subscriber.ts:145)
    at MapSubscriber.Subscriber.error (Subscriber.ts:115)
    at MapSubscriber.Subscriber._error (Subscriber.ts:145)
    at MapSubscriber.Subscriber.error (Subscriber.ts:115)
    at TapSubscriber._error (tap.js:sourcemap:75)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.umd.js:sourcemap:3881)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)`

**Comment by sboykova** [comment]
Hello,
Thank you for reporting this.
You can see working examples of tabs routing samples here:
[Tabs Routing 1](https://stackblitz.com/angular/olkvvnkjayp)
[Tabs Routing 2](https://stackblitz.com/angular/lpvlljnqobl)
In order to keep the samples browser application routing logic intact, these samples were designed to work independently on stackblitz only.

**Comment by sboykova** [comment]
The mentioned sample works only in stackbliz, provided additional information above.
Closing the issue because it is by design.
